# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./server-sql:/docker-entrypoint-initdb.d
      - dbdata6:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # networks:
    #   - sql_network

  server:
    # restart: always
    build:
      context: ./server-sql
      dockerfile: ./DockerfilePython
    ports:
      - 8000:8000
    depends_on:
      - db
    # networks:
    #   - sql_network

  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    volumes:
      - .:/docker_mongodb
      - /docker_mongodb/node_modules
      - /docker_mongodb/server-mongo
    depends_on:
      - server
    command: npm start
    # networks:
    #   - sql_network

volumes:
  dbdata6:
# networks:
#   sql_network:
#     driver: bridge
