# Use root/example as user/password credentials
version: "3.1"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  db:
    image: migration_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    image: python
    restart: on-failure
    build: .
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - PORT=8000
    depends_on:
      - db

  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/docker_mongodb
      - /docker_mongodb/node_modules
      - /docker_mongodb/server-mongo
    depends_on:
      - server
    command: npm start

volumes:
  db-data:
