# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: migration_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    image: nodejs
    restart: on-failure
    build: .
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - PORT=8000
    depends_on:
      - db

  backend:
    image: example/database
    volumes:
      - db-data:/etc/data

  backup:
    image: backup-service
    volumes: -db-data:/var/lib/backup/data

volumes: db-data
